
#SETEAR VENTANA
#screen = pygame.display.set_mode((ANCHO_VENTANA,ALTO_VENTANA))

#AL FINAL DEL BUCLE, MUESTRA TODO LO QUE CAMBIAMOS
#pygame.display.flip()

#OBJ
#POS-X-Y
#Auxiliar.getSurfaceFromSpriteSheet (LISTA DE FRAMES DE UNA ANIMACION)
#FRAME 0
#SPEED
#ANIMACION(LA ANIMACION CORRESPONDIENTE SEGUN EL MOMENTO)
#IMAGE (FRAME DE LA LISTA DE FRAMES CORRESPONDIENTE A ESE INSTANTE)
#RECT

#CHOQUE
#if  enemy.rect.colliderect(player.rect):